<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LTIN219936" failures="0" tests="7" name="testNGTestCases.SignInPage" time="0.055" errors="1" timestamp="2024-02-28T15:46:12 IST" skipped="6">
  <testcase classname="testNGTestCases.SignInPage" name="siteLaunch" time="0.051">
    <error message="Cannot invoke &quot;String.toLowerCase()&quot; because the return value of &quot;java.util.Properties.getProperty(String)&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "java.util.Properties.getProperty(String)" is null
at factory.BaseClass.initilizeBrowser(BaseClass.java:63)
at testNGTestCases.Setup.siteLaunch(Setup.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- siteLaunch -->
  <testcase classname="testNGTestCases.SignInPage" name="NavigateToUpcomingBikes" time="0.001">
    <skipped/>
  </testcase> <!-- NavigateToUpcomingBikes -->
  <testcase classname="testNGTestCases.SignInPage" name="UpcomingBikes" time="0.001">
    <skipped/>
  </testcase> <!-- UpcomingBikes -->
  <testcase classname="testNGTestCases.SignInPage" name="navigateToUsedCars" time="0.000">
    <skipped/>
  </testcase> <!-- navigateToUsedCars -->
  <testcase classname="testNGTestCases.SignInPage" name="usedCars" time="0.000">
    <skipped/>
  </testcase> <!-- usedCars -->
  <testcase classname="testNGTestCases.SignInPage" name="ClickonSignIn" time="0.001">
    <skipped/>
  </testcase> <!-- ClickonSignIn -->
  <testcase classname="testNGTestCases.SignInPage" name="captureSigninError" time="0.001">
    <skipped/>
  </testcase> <!-- captureSigninError -->
</testsuite> <!-- testNGTestCases.SignInPage -->
